#!/bin/sh
yq -Yi '(.spec.params[] | select(.name == "GIT_REPO").value) |="https://github.com/maximilianoPizarro/solicitud-credito-application"' pipeline-run.yaml
yq -Yi '(.spec.params[] | select(.name == "APP_JAR_VERSION").value) |="solicitud-credito-application-1.0.0-SNAPSHOT-runner.jar"' pipeline-run.yaml
